[tool.poetry]
name = "blog-backend"
version = "0.1.0"
description = ""
authors = ["endaaman <ken@endaaman.me>"]
readme = "README.md"
packages = [{include = "blog_backend"}]

[tool.poetry.scripts]
start = "blog_backend:start"

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.20.0"
fastapi = "^0.92.0"
watchdog = "^2.2.1"
pylint = "^2.16.2"
pydantic = "^1.10.5"
python-dotenv = "^0.21.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
